# Generated by Django 4.2.13 on 2026-06-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=500, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('variant', models.CharField(blank=True, max_length=200, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fragrance_flavor', models.CharField(blank=True, max_length=200, null=True)),
                ('promotion', models.CharField(blank=True, max_length=500, null=True)),
                ('addons', models.CharField(blank=True, max_length=500, null=True)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('image_paths', models.JSONField(blank=True, default=list)),
                ('confidence_scores', models.JSONField(blank=True, default=dict)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_duplicate_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_duplicates', to='products.imdbrecord')),
            ],
            options={
                'verbose_name': 'IMDB Record',
                'verbose_name_plural': 'IMDB Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
